[package]
edition = "2021"
name = "speakeasy-rust-sdk"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
# error handling
thiserror = "1.0"

# utils
chrono = {version = "0.4.22", default-features = false, features = ["alloc", "std", "clock"]}
har = "0.7.1"
once_cell = "1.14.0"
regex = "1.6.0"

# http
http = "0.2.8"

# serialization / deserialization
serde = {version = "1.0.144", features = ["derive"]}
serde_json = "1.0.85"

# logging
log = "0.4.17"
url = "2.3.1"

# misc

[dev-dependencies]
maplit = "1.0.2"
pretty_assertions = "1.3"
